databases:
  database_epika: epika_movies.db
  database_mediateka: mediateka_movies.db
  sample_queries:
  - SELECT * FROM movies WHERE genre = 'komedija';
  - SELECT * FROM movies WHERE duration > 90;
  - SELECT * FROM movies WHERE release_year < 1970;
  - "SELECT * FROM movies WHERE description LIKE '%nuotyki\u0173%';"
  - SELECT * FROM movies WHERE title LIKE '%dokumentinis%';
  - SELECT * FROM movies WHERE description LIKE '%dokumentinis%';
  - SELECT * FROM movies;
  - SELECT * FROM movies WHERE url IN (SELECT url FROM movies GROUP BY url HAVING
    COUNT(url) > 1);
  - SELECT * FROM movies WHERE title IN (SELECT title FROM movies GROUP BY title HAVING
    COUNT(title) > 1);
gui:
  app_name: CAAI Project 1 - scraping/SQLite3 app
  gui_window_size: 1900x800
scraping:
  lazy_scroll_step: 500
  list_of_genres_mediateka:
  - komedija
  - drama
  - trileris
  - "nuotyki\u0173"
  - elito
  - vaidybinis
  - pramoginis
  - "trumpametra\u017Eis"
  - dokumentinis
  - spektaklis
  - naujienos
  - "apybrai\u017Ea"
  list_search_strings_epika:
    long:
    - ant
    - ing
    - tai
    - kur
    - "d\u017Ei"
    - sta
    - gal
    - sav
    - pav
    - tar
    - tik
    - lab
    - vis
    - ger
    - tie
    - nie
    - art
    - met
    - kas
    - tuo
    - jau
    - "b\u016Bt"
    - vak
    - dar
    - man
    - sen
    - aps
    - tik
    - "\u0117jo"
    - nes
    - vie
    - lia
    - jim
    - ten
    - jos
    - "\u0161io"
    - "d\u0117l"
    - kit
    - dar
    - kai
    - pas
    - sak
    - prie
    - min
    - tur
    - kie
    - buv
    - mat
    - toj
    - "k\u0105*"
    - tam
    - "\u017Emo"
    - pri
    - pat
    - dir
    - pa*
    - pr*
    - ne*
    - ka*
    - te*
    - na*
    - jo*
    - ap*
    - da*
    - ja*
    - is*
    - ta*
    - ma*
    - ti*
    - ju*
    - no*
    - ko*
    - su*
    - sa*
    - ki*
    - me*
    - ga*
    - to*
    - la*
    - gr*
    - po*
    - ge*
    - di*
    - at*
    - ba*
    - nu*
    - se*
    - vi*
    - ku*
    - mi*
    - tr*
    - pi*
    - st*
    - va*
    - ie*
    - ma*
    - ri*
    - le*
    - ra*
    - ar*
    - am*
    - tu*
    - re*
    - bu*
    - as*
    - de*
    - an*
    - ir*
    - al*
    - mo*
    - a**
    - "\u0105**"
    - b**
    - c**
    - "\u010D**"
    - d**
    - e**
    - "\u0119**"
    - "\u0117**"
    - f**
    - g**
    - h**
    - i**
    - "\u012F**"
    - y**
    - j**
    - k**
    - l**
    - m**
    - n**
    - o**
    - p**
    - r**
    - s**
    - "\u0161**"
    - t**
    - u**
    - "\u0173**"
    - "\u016B**"
    - v**
    - z**
    - "\u017E**"
    - 0**
    - 1**
    - 2**
    - 3**
    - 4**
    - 5**
    - 6**
    - 7**
    - 8**
    - 9**
    - the
    - and
    - ing
    - her
    - ere
    - ent
    - tha
    - nth
    - was
    - eth
    - for
    - dth
    - hat
    - sth
    - thi
    - oft
    - ion
    - ter
    - res
    - ere
    - con
    - ver
    - all
    - his
    - ate
    - ons
    - ted
    - tho
    - nth
    - int
    - est
    - hen
    - rea
    - pro
    - out
    - are
    - oun
    - ill
    - our
    - eve
    - era
    - hes
    - ati
    - ear
    - ain
    - ess
    - ith
    - ted
    - ers
    - one
    - ast
    - not
    - ati
    - eve
    - tio
    - rat
    - ere
    - ell
    - end
    - act
    short:
    - komedija
    - "nuotyki\u0173"
  show_browser: false
  wait_time: 0.5
