# Application GUI settings
gui:
  app_description: CAAI Project 1 - Scraping/SQLite3 Application - scrape Epika LRT and Mediateka LRT
  window_size: 1900x800

# Database configurations
data:
  epika: data/epika_movies.db
  mediateka: data/mediateka_movies.db
  epika_demo: temp/epika_movies_demo.db
  mediateka_demo: temp/mediateka_demo.db

# Scraping settings
scraping:
  show_browser: false
  lazy_scroll_step: 500
  wait_time: 1  # Time between scrolling steps in sec

# Demo mode configurations
demo:
  is_demo: false
  default_demo_search_strings_epika: ["komedija", "nuotykiu"]
  num_demo_pages_mediateka: 2
