# Application GUI settings
gui:
  app_description: CAAI Project 1 - Scraping/SQLite3 Application - scrape Epika LRT and Mediateka LRT
  window_size: 1900x800

# Database configurations
databases:
  epika: epika_movies.db
  mediateka: mediateka_movies.db
  epika_demo: epika_movies_demo.db
  mediateka_demo: mediateka_demo.db

# Scraping settings
scraping:
  show_browser: false
  lazy_scroll_step: 500
  wait_time: 0.5  # Time between scrolling steps

# Demo mode configurations
demo:
  is_demo: false
  default_demo_search_strings_epika: ["komedija", "nuotykiu"]
  num_demo_pages_mediateka: 2
